### PR TITLE
Simplify Makefile

### PR DESCRIPTION
**Pull request by mibk**

### CODE REVIEW

**Comment by vanhalt** [comment]
LGTM :+1:

**Comment by vanhalt** [comment]
Question here, can we make the usage of `gccgo` available only if the system has it? Please

**Comment by mibk** [comment]
I myself don't have `gccgo` so I use `$ make GOC="go build"` to compile. But it could be done for example with these lines:
```make
GOC = go build -compiler gccgo
ifeq (, $(shell which gccgo 2>/dev/null))
	GOC = go build
endif
```

Should I update it?

**Comment by vanhalt** [comment]
That would be fantastic, to make the Makefile more generic. Dunno what @polegone thinks?

I would say :+1:

**Comment by polegone** [comment]
I don't think it matters what compiler people use, I just recommended gccgo because it makes smaller binaries.

Making it optional is fine with me.

**Comment by mibk** [comment]
What about making **gc** the default option as the binary size mostly doesn't matter? 

```make
CFLAGS = # empty
go build $(CFLAGS) -o $@ $<
```

If one wants to build it with `gccgo`, he/she would run `$ make CFLAGS="-compiler gccgo"`.

**Comment by polegone** [comment]
That sounds fine. I can note that option in the readme.

I can't merge anything now, however, as there is a conflict (I've updated the makefile since you made the pull request).

**Comment by polegone** [comment]
Will merge now.

**Pull request merged**
